/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clacess.Partido;
import Modelo.PartidoDAO;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author aron
 */
public class frmConsultaPartido extends javax.swing.JInternalFrame {

  Connection conex;
    ArrayList<Partido> lista = new ArrayList();
    PartidoDAO pd = new PartidoDAO();
    DefaultComboBoxModel<Object> combomodel = new DefaultComboBoxModel<>();
    public frmConsultaPartido() {
        initComponents();
          setLocation(200, 100);
        cargarCombo();
    }
        final void cargarCombo()
    {
        lista = pd.listarPartido();
        combomodel.addElement("Seleccionar Partido");
        cboPartido.setModel(combomodel);
        for(int i=0; i<lista.size();i++){
        combomodel.addElement(lista.get(i).getFechapart());
            }
        cboPartido.setModel(combomodel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboPartido = new javax.swing.JComboBox();
        btnGenRep = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Partidos:");

        btnGenRep.setText("Generar Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cboPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenRep)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenRep))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenRep;
    private javax.swing.JComboBox cboPartido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
