/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clacess.Equipo;
//import Clacess.Jugador;
import Conexion.Conexion;
import Modelo.EquipoDAO;
//import Modelo.JugadorDAO;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author aron
 */
public class frmJugadorEquipo extends javax.swing.JInternalFrame {
Connection conex;
    ArrayList<Equipo> lista = new ArrayList();
    EquipoDAO jd = new EquipoDAO();
    DefaultComboBoxModel<Object> combomodel = new DefaultComboBoxModel<>();
    public frmJugadorEquipo() {
        initComponents();
        setLocation(200, 100);
        cargarCombo();
    }
     final void cargarCombo()
    {
        lista = jd.listarEquipo();
        combomodel.addElement("Seleccionar Equipo");
        cboEquipo.setModel(combomodel);
        for(int i=0; i<lista.size();i++){
        combomodel.addElement(lista.get(i).getNombre());
            }
        cboEquipo.setModel(combomodel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGENREP = new javax.swing.JButton();
        Equipo = new javax.swing.JLabel();
        cboEquipo = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGENREP.setText("GENERAR REPORTES");
        btnGENREP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGENREPActionPerformed(evt);
            }
        });
        jPanel1.add(btnGENREP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        Equipo.setText("EQUIPO:");
        jPanel1.add(Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel1.add(cboEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGENREPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGENREPActionPerformed
        // TODO add your handling code here:
        String Equipo =null;
        JasperReport jasperReport = null;
        conex = Conexion.coneccion();
        Equipo = cboEquipo.getSelectedItem().toString();
        Map parametro = new HashMap();
        parametro.put("dist", Equipo);
        try{
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportess/report3.jasper"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametro, conex);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false);
            jasperViewer.setVisible(true);

        }catch(JRException ex){
            JOptionPane.showMessageDialog(null, "JasperReport:"+ex);
        }
    }//GEN-LAST:event_btnGENREPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipo;
    private javax.swing.JButton btnGENREP;
    private javax.swing.JComboBox cboEquipo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
