/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clacess.Campeonato;
//import Conexion.Coneccion;
import Conexion.Conexion;
import Modelo.CamponatoDAO;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author aron
 */
public class frmReportesCamp extends javax.swing.JInternalFrame {
Connection conex;
    CamponatoDAO cd = new CamponatoDAO();
    Campeonato cp = new Campeonato();
    ArrayList<Campeonato> lista = new ArrayList();
    DefaultComboBoxModel<Object> combomodel = new DefaultComboBoxModel<>();
    public frmReportesCamp() {
        initComponents();
        cargarCombo();
    }
    final void cargarCombo()
    {
        lista = cd.listarCampeonatos();
        combomodel.addElement("Seleccionar Campeonato");
        cboCampeonato.setModel(combomodel);
        for(int i=0; i<lista.size();i++){
        combomodel.addElement(lista.get(i).getNombre());
            }
        cboCampeonato.setModel(combomodel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCampeonato = new javax.swing.JComboBox();
        btnGenRept = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Campeonato:");

        btnGenRept.setText("Generar Reporte");
        btnGenRept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenReptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(cboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenRept)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenRept))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenReptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenReptActionPerformed
        // TODO add your handling code here:
        String campeonatos =null;
        JasperReport jasperReport = null;
        conex = Conexion.coneccion();
        campeonatos = cboCampeonato.getSelectedItem().toString();
        Map parametro = new HashMap();
        parametro.put("dist", campeonatos);
        try{
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportess/report1.jasper"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametro, conex);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false);
            jasperViewer.setVisible(true);

        }catch(JRException ex){
            JOptionPane.showMessageDialog(null, "JasperReport:"+ex);
        }
    }//GEN-LAST:event_btnGenReptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenRept;
    private javax.swing.JComboBox cboCampeonato;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
