/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clacess.Jugador;
import Clacess.Partido;
import Modelo.JugadorDAO;
import Modelo.PartidoDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author aron
 */
public class JugadorPartido extends javax.swing.JInternalFrame {

    DefaultComboBoxModel<Object> modelocombo = new DefaultComboBoxModel<>();
     DefaultComboBoxModel<Object> modelo = new DefaultComboBoxModel<>();
     ArrayList<Jugador>listaJugador;
     ArrayList<Partido>listaPartido;
     PartidoDAO pd = new PartidoDAO();
     JugadorDAO jd= new JugadorDAO();
    public JugadorPartido() {
        initComponents();
        cargarJugador();
        cargarPartido();
    }
        final void  cargarJugador()
    {
        modelocombo.addElement("selc. Jugador");
        cboJugador.setModel(modelocombo);
        listaJugador=jd.listarJugador();
        for(int i =0;i<listaJugador.size();i++)
        {
            modelocombo.addElement(listaJugador.get(i).getNombre());
        }
        cboJugador.setModel(modelocombo);
    } 
     final void  cargarPartido()
    {
        modelo.addElement("selc. Partido");
        cboPartido.setModel(modelo);
        listaPartido=pd.listarPartido();
            for(int i =0;i<listaPartido.size();i++)
        {
            modelo.addElement(listaPartido.get(i).getFechapart());
        }
        cboPartido.setModel(modelo);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboJugador = new javax.swing.JComboBox();
        cboPartido = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDJugador = new javax.swing.JTextField();
        txtIDPartido = new javax.swing.JTextField();
        txtCantGol = new javax.swing.JTextField();
        txtmingol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrpcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(cboJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        cboPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(cboPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        jLabel1.setText("Cant. Gol:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel2.setText("Min_Gol:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Jugador:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel5.setText("Partido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtIDJugador.setEnabled(false);
        getContentPane().add(txtIDJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 30));

        txtIDPartido.setEnabled(false);
        getContentPane().add(txtIDPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 50, 30));
        getContentPane().add(txtCantGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, -1));
        getContentPane().add(txtmingol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, -1));

        txtDescrpcion.setColumns(20);
        txtDescrpcion.setRows(5);
        jScrollPane1.setViewportView(txtDescrpcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Partido", "Min Gol", "Descripcion", "Cant. Gol"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJugadorActionPerformed
        // TODO add your handling code here:
        String jugador= cboJugador.getSelectedItem().toString();
        
        int id;
        int x= cboJugador.getSelectedIndex();
        if(x!=0)
        {
            id=jd.retornarIDjugador(jugador);
            txtIDJugador.setText(""+id);
        }
    }//GEN-LAST:event_cboJugadorActionPerformed

    private void cboPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPartidoActionPerformed
        // TODO add your handling code here:
        String partido= cboPartido.getSelectedItem().toString();
        
        int id;
        int x= cboPartido.getSelectedIndex();
        if(x!=0)
        {
            id=pd.retornarIDPartido(partido);
            txtIDPartido.setText(""+id);
        }
    }//GEN-LAST:event_cboPartidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboJugador;
    private javax.swing.JComboBox cboPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantGol;
    private javax.swing.JTextArea txtDescrpcion;
    private javax.swing.JTextField txtIDJugador;
    private javax.swing.JTextField txtIDPartido;
    private javax.swing.JTextField txtmingol;
    // End of variables declaration//GEN-END:variables
}
