/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clacess.Campeonato;
import Clacess.Jugador;
import Modelo.CamponatoDAO;
import Modelo.JugadorDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Aron
 */
public class JugadorCamp extends javax.swing.JInternalFrame {

    /**
     * Creates new form JugadorCamp
     */
     ArrayList<Jugador> lista = new ArrayList();
     ArrayList<Campeonato> list = new ArrayList();
    JugadorDAO jd = new JugadorDAO();
    CamponatoDAO  cd =new CamponatoDAO ();
    DefaultComboBoxModel<Object> combomodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Object> combomodelo = new DefaultComboBoxModel<>();
    public JugadorCamp() {
        initComponents();
        cargarComboCampeonato();
        cargarComboJugador();
        setLocation(150, 50);
    }
     final void cargarComboJugador()
    {
        lista = jd.listarJugador();
        combomodel.addElement("Seleccionar Jugador");
        cboJugador.setModel(combomodel);
        for(int i=0; i<lista.size();i++){
        combomodel.addElement(lista.get(i).getNombre());
            }
        cboJugador.setModel(combomodel);
    }
     final void cargarComboCampeonato()
    {
        list = cd.listarCampeonatos();
        combomodelo.addElement("Seleccionar Campeonato");
        cboCamponato.setModel(combomodelo);
        for(int i=0; i<list.size();i++){
        combomodelo.addElement(list.get(i).getNombre());
            }
        cboCamponato.setModel(combomodelo);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboJugador = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cboCamponato = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTR = new javax.swing.JTextField();
        txtTA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cboJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, -1));

        jLabel1.setText("Jugador:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(cboCamponato, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        jLabel2.setText("Campeonato:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "JUGADOR", "CAMPEONATO", "Nº ROJAS", "Nº AMARILLAS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 450, 110));
        getContentPane().add(txtTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, -1));
        getContentPane().add(txtTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, -1));

        jLabel3.setText("T.ROJAS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("T.AMARILLAS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        btnNuevo.setText("Nuevo");
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));

        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 40));

        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 500, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboCamponato;
    private javax.swing.JComboBox cboJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTA;
    private javax.swing.JTextField txtTR;
    // End of variables declaration//GEN-END:variables
}
