/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import java.util.Calendar;
//import pe.edu.upeu.sysacademico.control.ImagenFondo;
//import control.Imagenfondo;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
//import javax.swing.JInternalFrame;
/**
 *
 * @author Aron
 */
public class MENU extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Menup
     */
    public MENU() {
        initComponents();
        //JDATOS.setBorder(new Imagenfondo());
        mostrarFechaHora();
        setExtendedState(MAXIMIZED_BOTH);
    }
     public void imagenDP(Graphics g){
        Dimension tam = getSize();
        ImageIcon fondo = new ImageIcon(new ImageIcon(getClass().getResource("")).getImage());
        g.drawImage(fondo.getImage(), 0, 0, tam.width,tam.height,null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDATOS = new javax.swing.JDesktopPane();
        lblFecha = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMUsuario = new javax.swing.JMenuItem();
        jJugador = new javax.swing.JMenuItem();
        jitemEquipo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JDATOS.setBackground(new java.awt.Color(0, 255, 204));
        JDATOS.setForeground(new java.awt.Color(255, 255, 255));

        lblFecha.setBackground(new java.awt.Color(0, 255, 204));
        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 255, 153));

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<<");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(">>");

        javax.swing.GroupLayout JDATOSLayout = new javax.swing.GroupLayout(JDATOS);
        JDATOS.setLayout(JDATOSLayout);
        JDATOSLayout.setHorizontalGroup(
            JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDATOSLayout.createSequentialGroup()
                .addGap(976, 976, 976)
                .addGroup(JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JDATOSLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        JDATOSLayout.setVerticalGroup(
            JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDATOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addComponent(jLabel3))
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        JDATOS.setLayer(lblFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDATOS.setLayer(lblusuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDATOS.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDATOS.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDATOS.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("INICIO");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Knob Cancel.png"))); // NOI18N
        jMenuItem4.setText("SALIR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Cerrar secion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Knob Smart.png"))); // NOI18N
        jMenu2.setText("MANTENIMIENTO");

        jMenu3.setText("FORMULARIOS");

        jMenuItem1.setText("presidente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Partido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        JMUsuario.setText("Usuario");
        JMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(JMUsuario);

        jJugador.setText("Jugador");
        jJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJugadorActionPerformed(evt);
            }
        });
        jMenu3.add(jJugador);

        jitemEquipo.setText("Equipo");
        jitemEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemEquipoActionPerformed(evt);
            }
        });
        jMenu3.add(jitemEquipo);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Knob Shuffle On.png"))); // NOI18N
        jMenu4.setText("REPORTES");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Detalle jugador");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem6.setText("Consulta Campeonatos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Consulta Jugador");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JDATOS)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDATOS)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PRESIDENTE pr  = new PRESIDENTE();
        
       JDATOS.add(pr);
        pr.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void JMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMUsuarioActionPerformed
        
        FrmUsuario u = new FrmUsuario ();
        JDATOS.add(u);
        u.show();
        
    }//GEN-LAST:event_JMUsuarioActionPerformed

    private void jJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJugadorActionPerformed
      FromJugador  k = new FromJugador();
      JDATOS.add(k);
      k.show();
    }//GEN-LAST:event_jJugadorActionPerformed

    private void jitemEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemEquipoActionPerformed
        FormEquipo  k = new FormEquipo();
         JDATOS.add(k);
         k.show();
    }//GEN-LAST:event_jitemEquipoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JugadorCamp  k = new JugadorCamp ();
         JDATOS.add(k);
         k.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        formPartido p = new formPartido();
        JDATOS.add(p);
        p.show();
                
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Logueo l = new Logueo();
        l.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frmReportesCamp l = new frmReportesCamp();
        JDATOS.add(l);
        l.show();
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         frmJugadorEquipo l = new frmJugadorEquipo();
        JDATOS.add(l);
        l.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed
        /* public void CentrarVentana(JInternalFrame internalframe){
        int x = (JDATOS.getWidth() / 2) - internalframe.getWidth() / 2;
        int y = (JDATOS.getHeight()/2)-(internalframe.getHeight()/2);
        if(internalframe.isShowing()){
            internalframe.setLocation(x, y);
        }else{
        JDATOS.add(internalframe);
        internalframe.setLocation(x, y);
        internalframe.show();
        }
        }
    */
    
    void mostrarFechaHora(){

           Calendar Cal= Calendar.getInstance();
        String fec= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR)+" "+Cal.get(Cal.HOUR_OF_DAY)+":"+Cal.get(Cal.MINUTE)+":"+Cal.get(Cal.SECOND);
          lblFecha.setText(fec);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDATOS;
    private javax.swing.JMenuItem JMUsuario;
    private javax.swing.JMenuItem jJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jitemEquipo;
    private javax.swing.JLabel lblFecha;
    public static javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
//private void setContentPane(Imagenfondo desktop) {
  //      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

}
