/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;
import Clacess.Campeonato;
import Clacess.Equipo;
import Clacess.Presidente;
import Conexion.Conexion;
import Modelo.CamponatoDAO;
import Modelo.EquipoDAO;
import Modelo.PresidenteDAO;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aron
 */
public class PRESIDENTE extends javax.swing.JInternalFrame {
    DefaultTableModel model = new DefaultTableModel(); 
    PresidenteDAO pd = new PresidenteDAO();
     DefaultComboBoxModel<Object> modelocombo = new DefaultComboBoxModel<>();
     DefaultComboBoxModel<Object> modelo = new DefaultComboBoxModel<>();
    //Usuarios ud = new Usuarios ();
      ArrayList<Equipo>listaEquipo;
      ArrayList<Campeonato> listaCampeoanto;
      ArrayList<Presidente> listaPresidente = new ArrayList(); 
      EquipoDAO equipo = new EquipoDAO();
      CamponatoDAO camp= new CamponatoDAO();
    int op;
    Conexion cx = new Conexion();    
    Connection cn = cx.coneccion();
    //---------------------------------------------------------------------------------------------------
    public PRESIDENTE() {
        initComponents();
        btnBuscar.setEnabled(false);
        txtBuscar.setVisible(false);
        //----botones bloqueados  al iniciar
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        inabilitar();
        //---------------------------------
        txtDNI .setDocument(new LimiteJTextField(7));
        txtTelefono .setDocument(new LimiteJTextField(9));
        this.jANI.setEnabled(false);
        this.jANI.getCalendarButton().setEnabled(true);
        this.jFN.setEnabled(false);
        this.jFN.getCalendarButton().setEnabled(true);
        setLocation(40, 90);
        cargarEquipo();
        cargarCampeonato();
        listarPresidente();
        txtCodigo.setEnabled(false);
    }
    /*
void mostrarDatos(String valor)
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("EQUIPO");
        modelo.addColumn("Nombre");
        modelo.addColumn("AP.Paterno");
        modelo.addColumn("AP.Materno");
        modelo.addColumn("Posision");
        modelo.addColumn("Fecha Nacimiento");
       
        jdPRES.setModel(modelo);
        String sql ="";
        if(valor.equals(""))
        {
            sql="SELECT * FROM jugador";
        }
        else{
            sql="SELECT * FROM jugador WHERE Nombre='"+valor+"'";
        }
        String [] datos = new  String [7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
            }
            jdPRES.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    */
     final void  cargarEquipo()
    {
        modelocombo.addElement("selc. Equipo");
        cboEquipo.setModel(modelocombo);
        listaEquipo=equipo.listarEquipo();
        for(int i =0;i<listaEquipo.size();i++)
        {
            modelocombo.addElement(listaEquipo.get(i).getNombre());
        }
        cboEquipo.setModel(modelocombo);
    }
     final void  cargarCampeonato()
    {
        modelo.addElement("selc. campeonato");
        cboCampeonato.setModel(modelo);
        listaCampeoanto=camp.listarCampeonatos();
        for(int i =0;i<listaCampeoanto.size();i++)
        {
            modelo.addElement(listaCampeoanto.get(i).getNombre());
        }
        cboCampeonato.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaterno1 = new javax.swing.JTextField();
        jFN = new com.toedter.calendar.JDateChooser();
        jANI = new com.toedter.calendar.JDateChooser();
        cboEquipo = new javax.swing.JComboBox();
        txtIDEquipo = new javax.swing.JTextField();
        cboCampeonato = new javax.swing.JComboBox();
        txtIDCampeonato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdPRES = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRO PRESIDENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Presidente"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setText("Codigo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));

        txtPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaternoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));

        jLabel5.setText("Fecha  Nacimiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel6.setText("Ap.Paterno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 230, -1));

        jLabel7.setText("Ap Materno:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel8.setText("Año Inicio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel9.setText("Equipo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel10.setText("DNI:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        txtMaterno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaterno1KeyTyped(evt);
            }
        });
        jPanel1.add(txtMaterno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        jFN.setDateFormatString("yyyy-MM-dd\n");
        jPanel1.add(jFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 230, -1));

        jANI.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jANI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, -1));

        cboEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(cboEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, -1));

        txtIDEquipo.setEnabled(false);
        jPanel1.add(txtIDEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, -1));

        cboCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCampeonatoActionPerformed(evt);
            }
        });
        jPanel1.add(cboCampeonato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        txtIDCampeonato.setEnabled(false);
        jPanel1.add(txtIDCampeonato, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 70, -1));

        jLabel1.setText("Campeonato:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        jPanel1.add(cboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 50, -1));

        jLabel2.setText("SEXO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 390));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 380, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, 50));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 50));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 50));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 50));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 90, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 580, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Presidentes"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdPRES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Campeonato", "Equipo", "Nombre", "Ap.Paterno", "Ap.Materno", "DNI", "Sexo", "Fec. Nacimiento", "Fec. Presidente", "Telefono"
            }
        ));
        jdPRES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdPRESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jdPRES);
        if (jdPRES.getColumnModel().getColumnCount() > 0) {
            jdPRES.getColumnModel().getColumn(0).setMaxWidth(40);
            jdPRES.getColumnModel().getColumn(7).setMaxWidth(40);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 180));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 770, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        abilitar();
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAgregar.setEnabled(true);
        
        //___________________------
        txtCodigo.setText(null);
        txtNombre.setText(null);
        txtPaterno.setText(null);
        txtBuscar.setText(null);
        txtMaterno1.setText(null);
        txtBuscar.setText(null);
        txtDNI.setText(null);
        txtIDCampeonato.setText(null);
        txtIDEquipo.setText(null);
        txtTelefono.setText(null);
        cboCampeonato.setSelectedIndex(0); 
        cboEquipo.setSelectedIndex(0); 
        cboSexo.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String car= txtNombre.getText();
         if(!car.equals(""))//si es diferente de espacio que le exporte un mensaje.
       {
                int ide = Integer.parseInt(txtIDEquipo.getText());
                 int idc= Integer.parseInt(txtIDCampeonato.getText());
                String nombre = txtNombre.getText();
                String paterno= txtPaterno.getText();
                String materno= txtMaterno1.getText();
                String DNI= txtDNI.getText();
                String sexo= cboSexo.getSelectedItem().toString();
                String FechNaci= ((JTextField)jFN.getDateEditor().getUiComponent()).getText();
                String fechaDire= ((JTextField)jANI.getDateEditor().getUiComponent()).getText();
                String telefono= txtTelefono.getText();

                int z = pd.registrarPresidente(ide,idc, nombre,paterno,materno,DNI,sexo,FechNaci,fechaDire,telefono);

                if(z>0){

                    JOptionPane.showMessageDialog(this, "Guardado");
                    updateComponets();
                    //listarEquipo();
                    limpiar();
                }else{
                JOptionPane.showMessageDialog(this, "No se guardo");
                }
         }else{
         JOptionPane.showMessageDialog(null,"ingrese El nombre  Para continuar.","Error",JOptionPane.ERROR_MESSAGE);
           txtNombre.requestFocus();
         }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEquipoActionPerformed
        // TODO add your handling code here:
         String equipoa= cboEquipo.getSelectedItem().toString();
        
        int id;
        int x= cboEquipo.getSelectedIndex();
        if(x!=0)
        {
            id=equipo.retornarIDEquipo(equipoa);
            txtIDEquipo.setText(""+id);
        }
    }//GEN-LAST:event_cboEquipoActionPerformed

    private void cboCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCampeonatoActionPerformed
        // TODO add your handling code here:
        String equipoa= cboCampeonato.getSelectedItem().toString();
        
        int id;
        int x= cboCampeonato.getSelectedIndex();
        if(x!=0)
        {
            id=camp.retornarIDcampeonato(equipoa);
            txtIDCampeonato.setText(""+id);
        }
    }//GEN-LAST:event_cboCampeonatoActionPerformed

    private void jdPRESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdPRESMouseClicked
        // TODO add your handling code here:
        int fila=jdPRES.rowAtPoint(evt.getPoint());
        txtCodigo.setText(jdPRES.getValueAt(fila,0).toString());
        txtIDCampeonato.setText(jdPRES.getValueAt(fila,1).toString());
        txtIDEquipo.setText(jdPRES.getValueAt(fila,2).toString());
        txtNombre.setText(jdPRES.getValueAt(fila,3).toString());
        txtPaterno.setText(jdPRES.getValueAt(fila,4).toString());
        txtMaterno1.setText(jdPRES.getValueAt(fila,5).toString());
        txtDNI.setText(jdPRES.getValueAt(fila,6).toString());
        
        jFN.setDate(Date.valueOf(jdPRES.getValueAt(fila,8).toString()));
        jANI.setDate(Date.valueOf(jdPRES.getValueAt(fila,9).toString()));
        txtTelefono.setText(jdPRES.getValueAt(fila,10).toString());
        btnEliminar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_jdPRESMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         int fil = jdPRES.getSelectedRow();
        if(fil<0){
            JOptionPane.showMessageDialog(null, "Seleccionar El Presidente a MODIFICAR!");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea MODIFICAR el Presidente? "); 
            if(JOptionPane.OK_OPTION==confirmar) {
                   int id = Integer.parseInt(txtCodigo.getText());
                   int idcam= Integer.parseInt(txtIDCampeonato.getText());
                   int idequi=Integer.parseInt(txtIDEquipo.getText());
                    String nombre = txtNombre.getText();
                    String paterno = txtPaterno.getText();
                    String materno = txtMaterno1.getText();
                    String DNI = txtDNI.getText();
                    
                    //new String(txtclave.getPassword());
                     String fechaNaci= ((JTextField)jFN.getDateEditor().getUiComponent()).getText() ;
                     String fechaDirec= ((JTextField)jANI.getDateEditor().getUiComponent()).getText() ;
                     String telefono = txtTelefono.getText();
                    int x = pd.modificarPresidente(id,idcam,idequi,nombre,paterno,materno,DNI,fechaNaci,fechaDirec,telefono);
                    if(x==1){
                        JOptionPane.showMessageDialog(null, "Presidente MODIFICADO!");
                        updateComponets();
                        limpiar();
                        btnEliminar.setEnabled(false);
                        btnModificar.setEnabled(false);
                        btnAgregar.setEnabled(false);
                        
                        inabilitar();
                    }else{
                        JOptionPane.showMessageDialog(null, "El Presidente no se ha MODIFICADO!");      
                    }                   
            }        
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtDNIKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        /*  int fila = jdPRES.getSelectedRow();
        String cod="";
        cod=jdPRES.getValueAt(fila,0).toString();
        try {
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea ELIMINAR el  Presidente? "); 
            if(JOptionPane.OK_OPTION==confirmar) {
           
            PreparedStatement pst= cn.prepareStatement("DELETE FROM presidente WHERE idPresidente='"+cod+"'");
            pst.executeUpdate();
            updateComponets();
            limpiar();
            cboCampeonato.setSelectedIndex(0);
            }else{
                        JOptionPane.showMessageDialog(null, "Equipo no ELIMINADO!");      
                    } 
            
            
        } catch (Exception e) {
        }
        */
        
         int fila = jdPRES.getSelectedRow();
        if(fila<0){
            JOptionPane.showMessageDialog(null, "Seleccionar El Usuario a ELIMINAR");            
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea ELIMINAR el Usuario? "); 
            if(JOptionPane.OK_OPTION==confirmar) {
                    int celda = (int) jdPRES.getValueAt(fila, 0);
                    int x = pd.eliminarPresidente(celda);
                    if(x==1){
                        JOptionPane.showMessageDialog(null, "Usuario ELIMINADO!");
                        updateComponets();
                        limpiar();
                      cboCampeonato.setSelectedIndex(0);
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuario no ELIMINADO!");      
                    }                   
            } 
            
        } 
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if((a<'a' || a>'z')&&(a<'A')|a>'Z')evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaternoKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if((a<'a' || a>'z')&&(a<'A')|a>'Z')evt.consume();
    }//GEN-LAST:event_txtPaternoKeyTyped

    private void txtMaterno1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaterno1KeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if((a<'a' || a>'z')&&(a<'A')|a>'Z')evt.consume();
    }//GEN-LAST:event_txtMaterno1KeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarActionPerformed

void listarPresidente(){
    listaPresidente =pd.listarPresidente();
    model = (DefaultTableModel) jdPRES.getModel();
        Object[] usu = new Object[12];
        for(int i=0;i<listaPresidente.size();i++){
            usu[0]=listaPresidente.get(i).getIdpresidente();
            usu[1]=listaPresidente.get(i).getIdcampeonato();
            usu[2]=listaPresidente.get(i).getIdequipo();
            usu[3]=listaPresidente.get(i).getNombre();
            usu[4]=listaPresidente.get(i).getPaterno();
            usu[5]=listaPresidente.get(i).getMaterno();
            usu[6]=listaPresidente.get(i).getDni();
            usu[7]=listaPresidente.get(i).getSexo();
            usu[8]=listaPresidente.get(i).getFechanaci();
            usu[9]=listaPresidente.get(i).getFechapresi();
            usu[10]=listaPresidente.get(i).getTelefono();
            model.addRow(usu);
               
        jdPRES.setModel(model);
        } 
}
void limpiar(){
        txtCodigo.setText(null);
        txtBuscar.setText(null);
        txtDNI.setText(null);
        txtIDCampeonato.setText(null);
        txtNombre.setText(null);
        txtIDEquipo.setText(null);
        cboEquipo.setSelectedIndex(0);
        txtMaterno1.setText(null);
        txtPaterno.setText(null);
        txtTelefono.setText(null);
        
        }
void updateComponets(){
    LimpiarTabla(model);
    listarPresidente();
//    modelocombo.removeAllElements();
    //cargarCombo();
    //modelolista.clear();
    //cargarList();    
    }
    void LimpiarTabla(DefaultTableModel modelo){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){  
            modelo.removeRow(i);
        }
    }
    void inabilitar()
{
        txtCodigo.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPaterno.setEnabled(false);
        txtBuscar.setEnabled(false);
        txtMaterno1.setEnabled(false);
        cboEquipo.setEnabled(false); 
        cboCampeonato.setEnabled(false); 
        cboSexo.setEnabled(false); 
        txtDNI.setEnabled(false);
      this.jANI.setEnabled(false);
        this.jANI.getCalendarButton().setEnabled(true);
        this.jFN.setEnabled(false);
        this.jFN.getCalendarButton().setEnabled(true);
         txtTelefono.setEnabled(false);
}
void abilitar()
{
    txtCodigo.setEnabled(false);
        txtNombre.setEnabled(true);
        txtPaterno.setEnabled(true);
        txtBuscar.setEnabled(true);
        txtMaterno1.setEnabled(true);
        cboEquipo.setEnabled(true); 
        cboCampeonato.setEnabled(true); 
        cboSexo.setEnabled(true); 
        txtDNI.setEnabled(true);
        this.jANI.setEnabled(false);
        this.jANI.getCalendarButton().setEnabled(true);
        this.jFN.setEnabled(false);
        this.jFN.getCalendarButton().setEnabled(true);
         txtTelefono.setEnabled(true);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboCampeonato;
    private javax.swing.JComboBox cboEquipo;
    private javax.swing.JComboBox cboSexo;
    private com.toedter.calendar.JDateChooser jANI;
    private com.toedter.calendar.JDateChooser jFN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jdPRES;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtIDCampeonato;
    private javax.swing.JTextField txtIDEquipo;
    private javax.swing.JTextField txtMaterno1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
     
}
